# Generated by Django 3.2.8 on 2021-10-24 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccgg_api', '0002_auto_20211024_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pawn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
