# Generated by Django 3.2.8 on 2021-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccgg_api', '0003_pawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawn',
            name='pawn',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
