# Generated by Django 3.2.8 on 2021-10-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccgg_api', '0004_pawn_pawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawn',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pawn',
            name='pawn',
        ),
        migrations.AddField(
            model_name='pawn',
            name='indentifier',
            field=models.CharField(default='', max_length=15),
        ),
    ]
